name: Examen actions

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install sqlalchemy
        pip install fastapi
        pip install uvicorn
    - name: Analysing the code with pylint
      run: |
        pylint -d C0116,W0622 $(git ls-files '*.py')

  scan:
    runs-on: ubuntu-latest
    needs: pylint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  build:
    name: Docker push and build
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DH_USUARIO }}
          password: ${{ secrets.DH_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true 
          tags: ${{ secrets.DH_USUARIO }}/fastapi:latest

  aws:
    name: Deploy image to aws
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AMZ_IP }}
        username: ${{ secrets.AMZ_USUARIO }}
        key: ${{ secrets.AMZ_CLAVE }}
        port: 22 
        script: |
            sleep 40
            docker stop fastapi && docker rm fastapi
            docker rmi ${{ secrets.DH_USUARIO }}/fastapi
            docker run -d -p 80:8000 --name fastapi ${{ secrets.DH_USUARIO }}/fastapi

  test:
    name: test
    runs-on: ubuntu-latest
    needs: aws
    steps:
    - name: multiple command test
      uses: actions/test@v3
      with:
        script:
           curl http://54.226.176.135/status
           curl http://54.226.176.135/students/1